spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    ads-good-library:
      username: ads_goods_library_rw
      password: B8Y8N#AGrf9RbGVWl$
      driver-class-name: com.mysql.jdbc.Driver
      url: "jdbc:mysql://192.168.0.133:3306/ads_goods_library?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
task:
  pool:
    size: 2
